version: '1.0'

stages:
  - clone
  - build
  - push

steps:
  main_clone:
    stage: clone
    title: Cloning main repository
    type: git-clone
    repo: '${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}'
    revision: '${{CF_REVISION}}'

  build_image:
    stage: build
    type: build
    image_name: tivix/docker-nginx
    working_directory: ${{main_clone}}
    dockerfile: Dockerfile
    tag: ${{CF_SHORT_REVISION}}
    progress: tty

  push_image:
    stage: push
    image: tivix/docker-nginx
    candidate: ${{build_image}}
    tags:
      - latest
      - prod
    when:
    condition:
      all:
        noSkipCiInCommitMessage: 'includes(lower("${{CF_COMMIT_MESSAGE}}"), "release") == true'
        masterBranch: '"${{CF_BRANCH}}" == "master"'
