version: '3.7'

services:
  proxy:
    image: tivix/docker-nginx
    build:
      context: .
    ports:
      - 127.0.0.1:80:80
      - 127.0.0.1:443:443
    environment:
      - UPSTREAMS=/:service_a:80,/service_b:service_b:80
      - 'LOCATION_EXTRAS=/service_b:root /var/www;'
      - STATICS=/statics:/data/statics
      - REAL_IP_CIDRS=172.16.0.0/12
      - HTTPS_REDIRECT=false
      - BASIC_AUTH_LOCATIONS=/service_b
      - BASIC_AUTH_USER=user
      - BASIC_AUTH_PASS=pass
      - MICROCACHE=true
      - DEBUG=true
      - HEALTHCHECK=/health
      - HEALTHCHECK_LISTEN=0.0.0.0
      - STATS=/stats
      - NOSNIFF=true
      - CSP=true
      - CSP_SCRIPT_SRC=script-src.com
      - CSP_STYLE_SRC=style-src.com
      - CSP_IMG_SRC=img-src.com
      - CSP_CONNECT_SRC=connect-src.com
      - CSP_FONT_SRC=font-src.com
      - CSP_OBJECT_SRC=object-src.com
      - CSP_MEDIA_SRC=media-src.com
      - CSP_FRAME_SRC=frame-src.com
    depends_on:
      - service_a
      - service_b

  service_a:
    image: containous/whoami
    hostname: service_a

  service_b:
    image: containous/whoami
    hostname: service_b
