name: docker-nginx

on:
  push:
    tags:
      - v*

jobs:
  main:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: docker build --tag tivix/docker-nginx .
      - name: Check
        run: docker-compose run proxy test
      - name: Push
        run: |
          echo "${{ secrets.DOCKER_HUB_PASS }}" | docker login -u ${{ secrets.DOCKER_HUB_USER }} --password-stdin
          TAG=${GITHUB_REF##*/}
          echo "Pushing tag: ${TAG}"
          docker tag tivix/docker-nginx tivix/docker-nginx:${TAG}
          docker push tivix/docker-nginx:${TAG}
